# Generated by Django 5.0.6 on 2024-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('bodeguero', 'Bodeguero'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='viewer', max_length=20),
        ),
    ]
